### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [itsmiir/tooltipsplus#11]
Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

**Comment by itsmiir** [comment]
> Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?

1.19.3 is planned; i'm rather busy recently but it will happen Soon™️

**Comment by plushycat** [comment]
Hey, any plans to get this updated to 1.19.4?

**Comment by itsmiir** [comment]
1.19.4 and 1.20 betas should be released in the coming week

**Comment by itsmiir** [comment]
and by "week", of course i meant "two months"--versions through 1.20.1 are up on Modrinth
