### ISSUE TITLE
Shulker Box Tooltip

### ISSUE THREAD

**Issue by wontactcivilized** [itsmiir/tooltipsplus#13]
![image](https://github.com/itsmiir/tooltipsplus/assets/106423970/927f69d3-481d-4bad-833c-e1f4cf0e90d6)
Shulker Box Tooltip should be able to be disable from rendering when shulkerbox tooltips mods are installed

**Comment by itsmiir** [comment]
there is now a toggle for this feature in version 1.2.4 for 1.19 through 1.20.1--it's up on modrinth.
