### ISSUE TITLE
Freeze with completely transparent items

### ISSUE THREAD

**Issue by shedaniel** [itsmiir/tooltipsplus#14]
Easily reproducable with Tooltips+ and Immersive Armor

https://github.com/itsmiir/tooltipsplus/blob/f45803c3a8e8bb4aefdf81efd5b529b211355acd/src/main/java/com/miir/tooltipsplus/ColorFinder.java#L137

since the color is 0, it will never become readable.

**Comment by itsmiir** [comment]
thanks for the catch! edge case i forgot to think about

**Comment by DadoIrie** [comment]
I was actually the one having that issue - shedaniel was so kind and helped me out with that - and to be honest didn't thought it would be fixed that quick as the last issue was closed on nov 2022

loving your tooltips - thanks a lot

**Comment by DadoIrie** [comment]
Just saw that this merge happened for 1.19.3 and wondering if this would be compatible with 1.19.2 as not only that merge was changed, but also other stuff related to 1.19.3?
Besides that could you push the update onto modrinth? I've got no idea with building from source

**Comment by itsmiir** [comment]
Yeah, it'll be pushed later today when I get off work. I'm also publishing versions for 1.19.3 through 1.20.1

**Comment by itsmiir** [comment]
@dadoirie version 1.2.4 is now up on modrinth
