### ISSUE TITLE
Incompatible with librarian trade finder

### ISSUE THREAD

**Issue by Rozbiynk** [itsmiir/tooltipsplus#19]
latest log - https://mclo.gs/y1QItmN
crash report - https://mclo.gs/MFmdnZO
Minecraft 1.20.1
Quilt 1.19.1
Mod version in logs

**Comment by itsmiir** [comment]
it appears that ltf tries to [access tooltips before the client is initialized](https://github.com/Greeenman999/LibrarianTradeFinder/blob/b38a0dba7336f02c642e4b65ad3db16df867c14e/src/main/java/de/greenman999/config/TradeFinderConfig.java#L96), which tt+ is not expecting. it will probably be easier for me to fix this than the librariantradefinder devs.

**Comment by itsmiir** [comment]
fixed in [version 1.2.5](https://modrinth.com/mod/tooltipsplus/version/1.2.5+1.20)

**Comment by Rozbiynk** [comment]
thank
