### ISSUE TITLE
Tooltip+  overwriting resource packs

### ISSUE THREAD

**Issue by Scarlaid** [itsmiir/tooltipsplus#24]
For some reason `"numericalEnchants": false` despite being disabled still overwrite texture packs

Example for [Icons](https://www.curseforge.com/minecraft/texture-packs/icons) having custom icons for the enchantment levels

**Comment by Scarlaid** [comment]
### With Tooltip+
![image](https://github.com/itsmiir/tooltipsplus/assets/90851437/2e5d65fd-4f26-4ddb-a36d-17c3a3da8cce)

### Without Tooltip+
![image](https://github.com/itsmiir/tooltipsplus/assets/90851437/67d451e6-bf1e-4ba0-ac2e-237a2994eb79)

_Potion and other stuff is not affected_

**Comment by itsmiir** [comment]
![image](https://github.com/itsmiir/tooltipsplus/assets/12114517/59b97eb1-11a7-4105-a2aa-f09db09d1f84)
seems to be a known incompatibility with icons. the resource pack expects vanilla strings there, which isn't the case obviously with tt+. `wontfix` for now, may return to this in the future.

**Comment by Scarlaid** [comment]
welp, for the time being I will just be going to remove the mixin `EnchantmentEnhancementMixin` in `tooltipplus.mĩnixn.json` until a compat fix was pushed

Not breaking anything, I hope so. No enchantment color butt I guess i can live with it 🦆
