### ISSUE TITLE
Incompatible with FZMM or EMI Loot

### ISSUE THREAD

**Issue by Rozbiynk** [itsmiir/tooltipsplus#25]
https://mclo.gs/nfxaJTr
com.miir.tooltipsplus.ExtraTooltips.addBeehiveTooltip

**Comment by Rozbiynk** [comment]
bump

**Comment by Rozbiynk** [comment]
any updates?

**Comment by itsmiir** [comment]
hi, this is on my to-do list. i dont have a ton of time to do minecraft modding right now, but it _is_being worked on.

**Comment by itsmiir** [comment]
resolved in [1.2.6](https://modrinth.com/mod/tooltipsplus/version/1.2.6+1.20)
