### ISSUE TITLE
Conflict with tweakermore

### ISSUE THREAD

**Issue by x-yingcan-x** [itsmiir/tooltipsplus#3]
tweakermore:[https://github.com/Fallen-Breath/tweakermore/issues/20](https://github.com/Fallen-Breath/tweakermore/issues/20)
It seems to be a conflict caused by the modification of the shulker box, may be fixed, or disable the shulker box related features when tweakermore exists
Mechanical translation, I'm sorry

**Comment by itsmiir** [comment]
fixed in [latest release](https://modrinth.com/mod/tooltipsplus/version/1.2.2)
