### ISSUE TITLE
Reinforced Shulker Boxes compat

### ISSUE THREAD

**Issue by DadoIrie** [itsmiir/tooltipsplus#5]
could I ask for Reinforced Shulker Boxes (https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes) compatibility on fabric 1.18.2?
thanks a lot

**Comment by itsmiir** [comment]
what is the compat issue? from what i can see it should work fine. is it a crash or is the tooltip just not displaying?

**Comment by DadoIrie** [comment]
I looked into it right now and gotta apologize as it might have been a conflict with another mod ... basically the issue was that only vanilla shulkers had tooltips while the modded ones (reinforced shulkers) not ... that issue is no more and I'm closing this ticket (most likely was *overworked* myself and have taken the weekend off)
sorry again

**Comment by itsmiir** [comment]
no problem! thanks for using my mod :)
