### ISSUE TITLE
[Client connection Problem] - Can't connect to a world -  Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [itsmiir/tooltipsplus#8]
Hey there, 

when your mod is installed on the client, i cant connect to a singleplayer world / multiplayer world...
Both not working , client is stuck somehow.

No crash log or console entries

Fabric 1.19.2
Fabric Loader 0.14.9
ToolTip+ 1.3.0

**Comment by itsmiir** [comment]
i have no trouble with 1.3.0+1.19/fabric loader 0.14.9 on 1.19.2. perhaps it's another of your mods?
without a crash report or logs i can't really do anything

**Comment by xR4YM0ND** [comment]
[client latest.log](https://gist.github.com/SpigotDE/b558d3b1a7919c05b14d5fb5ef88d5dd)

i closed the game after ~ 3 mins stuck on "Joining World..."

**Comment by itsmiir** [comment]
doesn't seem to be a tooltipsplus issue... if you remove only tooltipsplus does the issue persist?

**Comment by xR4YM0ND** [comment]
No, it only happens when i add Tooltipplus

**Comment by xR4YM0ND** [comment]
Maybe its a mod of those:
https://www.curseforge.com/minecraft/mc-mods/tooltipfix
https://www.curseforge.com/minecraft/mc-mods/equipment-compare-fabric
https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions

**Comment by xR4YM0ND** [comment]
Or its Anivl Display 
https://www.curseforge.com/minecraft/mc-mods/anvil-display

**Comment by itsmiir** [comment]
i'm not sure what's causing this, but i don't see how it could be tooltipsplus...
i'd recommend a binary search-- remove half your modlist and see if the problem persists; if it does, remove half of your remaining mods; if it doesn't, put back half of the mods you removed.
