### ISSUE TITLE
[1.19.2] Incompatible with Origins mod

### ISSUE THREAD

**Issue by ConqAra** [itsmiir/tooltipsplus#9]
Crash upon trying to load this mod with Origins.

[Crashlog](https://paste.ee/p/TGCji)

**Comment by itsmiir** [comment]
it looks like one of your other mods is removing some code that tooltipsplus needs to work. i'm working on an update that may make the mod more resilient to things like that. until then, i'd recommend a binary search-- remove half your modlist and see if the problem persists; if it does, remove half of your remaining mods; if it doesn't, put back half of the mods you removed.
